-- 006_active_params.sql
-- Single-source-of-truth table: one row per tuning period = the best params for live trading.

CREATE TABLE IF NOT EXISTS active_params (
    id UUID NOT NULL,
    period VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sweep_name TEXT NOT NULL DEFAULT '',
    -- Metrics
    sharpe DOUBLE PRECISION NOT NULL,
    total_return_pct DOUBLE PRECISION NOT NULL,
    max_drawdown_pct DOUBLE PRECISION NOT NULL,
    profit_factor DOUBLE PRECISION NOT NULL,
    win_rate_pct DOUBLE PRECISION NOT NULL,
    num_trades INTEGER NOT NULL,
    ret_dd_ratio DOUBLE PRECISION NOT NULL,
    -- Param columns (identical to param_snapshots)
    SHORT_WINDOW INTEGER NOT NULL DEFAULT 24,
    MED_WINDOW INTEGER NOT NULL DEFAULT 48,
    MED2_WINDOW INTEGER NOT NULL DEFAULT 96,
    LONG_WINDOW INTEGER NOT NULL DEFAULT 144,
    EMA_FAST INTEGER NOT NULL DEFAULT 28,
    EMA_SLOW INTEGER NOT NULL DEFAULT 104,
    RSI_PERIOD INTEGER NOT NULL DEFAULT 32,
    RSI_BULL INTEGER NOT NULL DEFAULT 50,
    RSI_BEAR INTEGER NOT NULL DEFAULT 50,
    RSI_OVERBOUGHT INTEGER NOT NULL DEFAULT 69,
    RSI_OVERSOLD INTEGER NOT NULL DEFAULT 31,
    MACD_FAST INTEGER NOT NULL DEFAULT 56,
    MACD_SLOW INTEGER NOT NULL DEFAULT 92,
    MACD_SIGNAL INTEGER NOT NULL DEFAULT 36,
    BB_PERIOD INTEGER NOT NULL DEFAULT 28,
    FUNDING_LOOKBACK INTEGER NOT NULL DEFAULT 96,
    FUNDING_BOOST DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    BASE_POSITION_PCT DOUBLE PRECISION NOT NULL DEFAULT 0.08,
    VOL_LOOKBACK INTEGER NOT NULL DEFAULT 144,
    TARGET_VOL DOUBLE PRECISION NOT NULL DEFAULT 0.015,
    ATR_LOOKBACK INTEGER NOT NULL DEFAULT 96,
    ATR_STOP_MULT DOUBLE PRECISION NOT NULL DEFAULT 5.5,
    TAKE_PROFIT_PCT DOUBLE PRECISION NOT NULL DEFAULT 99.0,
    BASE_THRESHOLD DOUBLE PRECISION NOT NULL DEFAULT 0.012,
    BTC_OPPOSE_THRESHOLD DOUBLE PRECISION NOT NULL DEFAULT -99.0,
    PYRAMID_THRESHOLD DOUBLE PRECISION NOT NULL DEFAULT 0.015,
    PYRAMID_SIZE DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    CORR_LOOKBACK INTEGER NOT NULL DEFAULT 288,
    HIGH_CORR_THRESHOLD DOUBLE PRECISION NOT NULL DEFAULT 99.0,
    DD_REDUCE_THRESHOLD DOUBLE PRECISION NOT NULL DEFAULT 99.0,
    DD_REDUCE_SCALE DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    COOLDOWN_BARS INTEGER NOT NULL DEFAULT 8,
    MIN_VOTES INTEGER NOT NULL DEFAULT 4,
    THRESHOLD_MIN DOUBLE PRECISION NOT NULL DEFAULT 0.005,
    THRESHOLD_MAX DOUBLE PRECISION NOT NULL DEFAULT 0.02,
    BB_COMPRESS_PCTILE INTEGER NOT NULL DEFAULT 90,

    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_active_params_period ON active_params(period);
CREATE INDEX IF NOT EXISTS idx_active_params_created_at ON active_params(created_at);

-- RLS: enable + allow-all policy (same pattern as 005_param_snapshots.sql)
DO $$
BEGIN
    ALTER TABLE active_params ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN others THEN NULL;
END $$;

DO $$
BEGIN
    CREATE POLICY "Allow all access" ON active_params FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
